name       : sqlitebrowser
version    : 3.9.1
release    : 2
source     :
    - https://github.com/sqlitebrowser/sqlitebrowser/archive/3.9.1.tar.gz : 4ff7da5c539269195bca9d25e7dc30518ba8b7a59f6231432cdc3d7222832af7
license    : GPL-3.0
component  : programming.tools
summary    : DB Browser for SQLite
description: |
    DB Browser for SQLite is a high quality, visual, open source tool to create, design, and edit database files compatible with SQLite.
builddeps  :
    - pkgconfig(QtCore)
    - pkgconfig(sqlite3)
setup      : |
    %cmake -DQT_MOC_EXECUTABLE=/usr/bin/moc-qt4 \
           -DQT_RCC_EXECUTABLE=/usr/bin/rcc-qt4 \
           -DQT_UIC_EXECUTABLE=/usr/bin/uic-qt4 \
           .
build      : |
    %make
install    : |
    %make_install
