name       : sqlitebrowser
version    : 3.10.1
release    : 3
source     :
    - https://github.com/sqlitebrowser/sqlitebrowser/archive/v3.10.1.tar.gz : 36eb53bc75192c687dce298c79f1532c410ce4ecbeeacfb07b9d02a307f16bef
license    : GPL-3.0
component  : programming.tools
summary    : DB Browser for SQLite
description: |
    DB Browser for SQLite is a high quality, visual, open source tool to create, design, and edit database files compatible with SQLite.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sqlite3)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
