name       : sqlitebrowser
version    : 3.8.0
release    : 1
source     :
    - https://github.com/sqlitebrowser/sqlitebrowser/archive/v3.8.0.tar.gz : f638a751bccde4bf0305a75685e2a72d26fc3e3a69d7e15fd84573f88c1a4d92
license    : GPL-3.0
component  : programming.tools
summary    : DB Browser for SQLite
description: |
    DB Browser for SQLite is a high quality, visual, open source tool to create, design, and edit database files compatible with SQLite.
builddeps  :
    - pkgconfig(QtCore)
    - pkgconfig(sqlite3)
setup      : |
    %cmake -DQT_MOC_EXECUTABLE=/usr/bin/moc-qt4 \
           -DQT_RCC_EXECUTABLE=/usr/bin/rcc-qt4 \
           -DQT_UIC_EXECUTABLE=/usr/bin/uic-qt4 \
           .
build      : |
    %make
install    : |
    %make_install
