name       : sqlitebrowser
version    : 3.12.2
release    : 9
source     :
    - https://github.com/sqlitebrowser/sqlitebrowser/archive/v3.12.2.tar.gz : 645f98d38e5d128a449e93cebf03c8070f9eacd2d16b10e433a781d54a9d478a
license    :
    - GPL-3.0-or-later
    - MPL-2.0
component  : programming.tools
summary    : DB Browser for SQLite
description: |
    DB Browser for SQLite (DB4S) is a high quality, visual, open source tool to create, design, and edit database files compatible with SQLite.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sqlite3)
setup      : |
    %cmake -DENABLE_TESTING=ON .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
